# Example Site settings

#google_analytics: UA-NNNNNNNN-N
title: QR
header_pages:
 - index.md
 - projects.md
 - tools.md
 - about.md

footer: 'follow me on <a href="https://twitter.com/qrbounty">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)
